# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Spotify Search' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


  	pod 'Alamofire', '~> 4.7'


  target 'Spotify SearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Spotify SearchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
